### ISSUE TITLE
Broken Workstream w/ 1 participant

### ISSUE THREAD

**Issue by IanBoucherTru** [bitbeckers/fux-dapp#23]
User able to spin up workstream with only 1 participant but blocked from finalizing

<img width="565" alt="image" src="https://user-images.githubusercontent.com/41161280/217872107-741620cc-0a03-458c-946d-ce839469b987.png">

**Comment by bitbeckers** [comment]
We've added a closing flow that does not require evaluations and does not payout vFUX
