### ISSUE TITLE
Submitting less than 100 vFUX in evaluation stage?

### ISSUE THREAD

**Issue by IanBoucherTru** [bitbeckers/fux-dapp#24]
Should we enable users to submit less than 100 vFUX each evaluation step?

For a situation of 2 contributors, only option is to give all vFUX to the other contributor. If we allow Workstream creation with less than 3 people then we should disable evaluation step

<img width="668" alt="image" src="https://user-images.githubusercontent.com/41161280/217872409-54c64a11-9e53-44dd-aedd-2c756c5dc51b.png">

**Comment by bitbeckers** [comment]
Flow available where the evaluation step is skipped
